# Exercices SQL avec SQLite 🗄️

Dans ce notebook on va :
1. Créer une base de données SQLite directement en Python
2. La remplir avec des données réalistes (ventes d'une boutique)
3. Résoudre 10 exercices SQL progressifs

Aucun logiciel supplémentaire — SQLite est intégré à Python !

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")
cursor = conn.cursor()
print("✅ Connexion SQLite OK")

✅ Connexion SQLite OK

In [2]:
cursor.executescript("""
CREATE TABLE clients (
    id_client INTEGER PRIMARY KEY,
    nom TEXT, ville TEXT, age INTEGER
);
INSERT INTO clients VALUES
    (1,'Amira Benali','Paris',34),
    (2,'Karim Messad','Lyon',28),
    (3,'Sofia Dupont','Paris',45),
    (4,'Yacine Hadj','Marseille',31),
    (5,'Lina Morel','Lyon',22),
    (6,'Omar Saidi','Paris',38),
    (7,'Nadia Leroux','Bordeaux',27),
    (8,'Rayan Chaoui','Marseille',52);

CREATE TABLE produits (
    id_produit INTEGER PRIMARY KEY,
    nom TEXT, categorie TEXT, prix REAL
);
INSERT INTO produits VALUES
    (1,'Laptop Pro','Informatique',1200.00),
    (2,'Souris sans fil','Informatique',25.00),
    (3,'Clavier mécanique','Informatique',89.00),
    (4,'Écran 27 pouces','Informatique',350.00),
    (5,'Bureau standing','Mobilier',450.00),
    (6,'Chaise ergonomique','Mobilier',320.00),
    (7,'Lampe de bureau','Mobilier',45.00),
    (8,'Webcam HD','Informatique',79.00);

CREATE TABLE commandes (
    id_commande INTEGER PRIMARY KEY,
    id_client INTEGER, id_produit INTEGER,
    quantite INTEGER, date_cmd TEXT
);
INSERT INTO commandes VALUES
    (1,1,1,1,'2024-01-15'),(2,1,2,2,'2024-01-15'),
    (3,2,3,1,'2024-01-20'),(4,3,5,1,'2024-02-03'),
    (5,3,6,1,'2024-02-03'),(6,4,2,3,'2024-02-10'),
    (7,5,8,1,'2024-02-14'),(8,6,4,2,'2024-03-01'),
    (9,6,1,1,'2024-03-01'),(10,7,7,2,'2024-03-15'),
    (11,8,3,1,'2024-03-20'),(12,2,8,1,'2024-04-02'),
    (13,1,6,1,'2024-04-10'),(14,5,1,1,'2024-04-18'),
    (15,3,2,4,'2024-04-25');
""")
print("✅ 8 clients · 8 produits · 15 commandes créés")

✅ 8 clients · 8 produits · 15 commandes créés

In [3]:
# Cette fonction nous permet d'écrire les requêtes simplement
def sql(query):
    return pd.read_sql_query(query, conn)

# Test — affiche les clients
sql("SELECT * FROM clients")

   id_client           nom      ville  age
0          1  Amira Benali      Paris   34
1          2  Karim Messad       Lyon   28
2          3  Sofia Dupont      Paris   45
3          4   Yacine Hadj  Marseille   31
4          5    Lina Morel       Lyon   22
5          6    Omar Saidi      Paris   38
6          7  Nadia Leroux   Bordeaux   27
7          8  Rayan Chaoui  Marseille   52

In [4]:
# Exercice 1 — Affiche tous les clients
sql("SELECT * FROM clients")

   id_client           nom      ville  age
0          1  Amira Benali      Paris   34
1          2  Karim Messad       Lyon   28
2          3  Sofia Dupont      Paris   45
3          4   Yacine Hadj  Marseille   31
4          5    Lina Morel       Lyon   22
5          6    Omar Saidi      Paris   38
6          7  Nadia Leroux   Bordeaux   27
7          8  Rayan Chaoui  Marseille   52

In [5]:
# Exercice 2 — Affiche uniquement le nom et la ville
sql("SELECT nom, ville FROM clients")

            nom      ville
0  Amira Benali      Paris
1  Karim Messad       Lyon
2  Sofia Dupont      Paris
3   Yacine Hadj  Marseille
4    Lina Morel       Lyon
5    Omar Saidi      Paris
6  Nadia Leroux   Bordeaux
7  Rayan Chaoui  Marseille

In [8]:
# Exercice 3 — Affiche uniquement les clients qui habitent à Paris
sql("SELECT nom FROM clients WHERE ville = 'Paris'")

            nom
0  Amira Benali
1  Sofia Dupont
2    Omar Saidi

In [13]:
# Affiche les clients de moins de 30 ans, 
# triés du plus jeune au plus âgé
sql("SELECT nom, age FROM clients WHERE age < 30 ORDER BY age ASC")

            nom  age
0    Lina Morel   22
1  Nadia Leroux   27
2  Karim Messad   28

In [15]:
# Question A : combien y a-t-il de clients au total ?
sql("SELECT COUNT (nom) AS nb_clients FROM clients")

   nb_clients
0           8

In [16]:
# Question B : quel est l'âge moyen des clients ?
sql("SELECT ROUND(AVG(age), 1) AS age_moyen FROM clients")

   age_moyen
0       34.6

In [17]:
# Combien de clients par ville ?
# Trie par nombre décroissant
sql("SELECT ville, COUNT(*) AS nb_clients FROM clients GROUP BY ville ORDER BY nb_clients DESC")

       ville  nb_clients
0      Paris           3
1  Marseille           2
2       Lyon           2
3   Bordeaux           1

In [22]:
# Quelles villes ont PLUS D'UN client ?
sql("""
SELECT ville, COUNT(*) AS nb_clients
FROM clients
GROUP BY ville
HAVING nb_clients > 1
""")

       ville  nb_clients
0       Lyon           2
1  Marseille           2
2      Paris           3